services:
  - type: worker
    env: node
    name: github-issues-to-notion
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
